### PR TITLE
Pull victims2

### PR DESCRIPTION
**Pull request by AdVetter**
the last victims

### CODE REVIEW

**Comment by heinrich5991** [comment]
Have you tested it?

**Comment by AdVetter** [comment]
Yes, it works like before (without https://github.com/GreYFoX/teeworlds/commit/27c1a82900deca7c0512f35ce017f537228a61db)

**Comment by ravomavain** [comment]
@XXLTomate: what do you mean by without that commit? That this pull request fix the whole force-pause bug or that the commit 27c1a829 broke  this pull request?

**Comment by AdVetter** [comment]
@ravomavain: no, only that your commit was made after mine, so I could not test force_pause.
But because the Victim thing is already in your commit, it should work.

**Pull request merged**
