### PR TITLE
Removed old pause as its a cheat

### PR DESCRIPTION
**Pull request by Learath2**

### CODE REVIEW

**Comment by heinrich5991** [comment]
So you rather want people to cheat by forcepausing? It's exactly as easy as /pause, if you really want to cheat. :)

**Comment by Learath2** [comment]
@heinrich5991 I don't care if they want to wait a minimum of 2 mins or more just to cheat and if we want it removed its just 4 or 5 lines at most 10 lines.

**Comment by GreYFoX** [comment]
Merged locally on 0.7

**Comment by GreYFoX** [comment]
P.S. i support @heinrich5991 1 commit for 1 thing, but when i merged, i changed your commit message @Learath2

**Comment by Learath2** [comment]
Well i never said that heinrich was wrong im just lazy

**Pull request closed without merging**
