### PR TITLE
Enhance pausing system (by @heinrich5991)

### LINKED ISSUE #124: force pause/vote player to spectate doesn't work
Using the latest sources, if admin uses force_pause on player, it doesn't work. Same for if player votes another player to spectator

### PR DESCRIPTION
**Pull request by ravomavain**
- enhance /pause (@heinrich5991)
- add /spec command to pause without leaving the game (@heinrich5991)
- if sv_pauseable is set to 0, /pause behave as /spec (@heinrich5991)
- should fix #124 and #127 (@ravomavain)

### CODE REVIEW

**Comment by senyai** [comment]
So `sv_pauseable 0` will allow to go to pause using /spec, right? Sounds wrong to me.

**Comment by ravomavain** [comment]
Since /spec doesn't remove the tee from the game, it can't be used to cheat like /pause. The only "cheat" that can be done with /spec is seeing the rest of the map, which you can already do easily with map editor or aseconde client on spectator mode. So since /spec doesn't introduce any cheats, there's no particular reason to disable it.
Whatever, if you really want it, we can add a new config variable to disable /spec... but remember that people can also reproduce the same feature with client side mod so that the config variable will be useless...

**Comment by heinrich5991** [comment]
This pull request cannot be automatically merged. Could you update it, @ravomavain ?

**Comment by ravomavain** [comment]
Updated, should now merge without conflict (even fast forward if @GreYFoX didn't added other commits ;-) )

**Comment by GreYFoX** [comment]
merged

**Pull request closed without merging**
