### PR TITLE
Untitled

### PR DESCRIPTION
**Pull request by EliteKuchen**

### CODE REVIEW

**Comment by AdVetter** [comment]
what about ?v

**Comment by ravomavain** [comment]
I think it will be better to use 'left me' to move oneself and to use 'left id' to move another player (like we do with super me/super id). Theses commands have been made to work like that (i think), but there is a little bug that prevent it to work (cf. pull request 18).

**Comment by GreYFoX** [comment]
Sorry Won't Add, it's wanted that you could move others.

**Comment by ravomavain** [comment]
I fixed it (cf. https://github.com/GreYFoX/DDRace/pull/18), GreYFoX will commit it soon.

**Pull request closed without merging**
